### ISSUE TITLE
Firebase Cloud Functions supported?

### ISSUE THREAD

**Issue by ShaMan123** [utatti/express-formidable#21]
Does this module work with Firebase Cloud Functions?
I get strange behavior.

**Comment by francescov1** [comment]
I'm getting the same error. [Multer](https://github.com/expressjs/multer) is not compatible with Firebase Functions so I wouldn't be surprised if this isn't either.

**Comment by ShaMan123** [comment]
Use `busboy`. 
Take into account that AFAIK and if it hasn't been fixed yet, testing cloud functions with a Firebase/Google local emulator behaves differently than a deployed function. 
Google infrastructure adds middleware to every function, changing the request body.
It parses the `body` to whatever it thinks it is (good for `json` not for `multiform data`) and creates a clone of the original `body` named `rawBody`.
Read more: [PR with code example](https://github.com/ShaMan123/functions-samples/pull/1)

**Comment by cdstamper** [comment]
@francescov1 
> I'm getting the same error. [Multer](https://github.com/expressjs/multer) is not compatible with Firebase Functions so I wouldn't be surprised if this isn't either.

multer is fine with Firebase Functions, you just need to specify a directory in /tmp (the rest of the filesystem is read-only).

I'm seeing this error when app.use(formidable()) is hanging. The function times out and terminates (the termination causes the error you see).

@ShaMan123 for what it's worth, you can bypass google's Express fork by returning Express App of your own rather than a function:
`exports.myExpressFunction = functions.https.onRequest(myExpressAppInstance);`

**Comment by ShaMan123** [comment]
@francescov1 I've stopped using this lib with firebase and stopped using onRequest with multipart data but...
Though I didn't understand your suggestion (so sorry if my reply is complete nonsense), to my understanding the reason busboy works and formidable doesn't is because you can configure where it reads the request from. This way you configure it to read the `rawRequest` attribute instead of the `body` attribute or whatever. 
I'm guessing you could pipe the `rawRequest` through formidable and get it working in the function's body itself, not in the middleware.
